import type { LockFile } from "../types";
import { fileExists, readTextFile, writeTextFile } from "../utils/fs";
import { dumpYaml, parseYaml } from "../utils/yaml";

export async function readLockFile(lockPath: string): Promise<LockFile | null> {
	if (!(await fileExists(lockPath))) return null;
	const content = await readTextFile(lockPath);
	return parseYaml<LockFile>(content);
}

export async function writeLockFile(
	lockPath: string,
	lock: LockFile,
): Promise<void> {
	const header = "# Auto-generated by prsm. Do not edit manually.\n";
	await writeTextFile(lockPath, header + dumpYaml(lock));
}

export function createLockFile(
	presets: Record<string, { version: string; url: string; checksum: string }>,
): LockFile {
	return {
		version: 1,
		presets,
		resolvedAt: new Date().toISOString(),
	};
}
